update git pre-commit git hook to do gofmt before commit

diff --git a/git-hooks/go/pre-commit b/git-hooks/go/pre-commit
--- a/git-hooks/go/pre-commit
+++ b/git-hooks/go/pre-commit
@@ -2,9 +2,16 @@
 # redirect
 exec 1>&2
 
+go fmt ./...
+
 go install
 if [ $? != 0 ]  ; then
     echo "does not compile"
+    exit 1
+fi
+go test ./...
+if [ $? != 0 ] ; then
+    echo "tests fail"
     exit 1
 fi
 echo "we gud"
